### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by daniellangh** [jVirus/expandable-collection-view-kit#6]
Please add an example app for easier testing.
Right now including the package in swift package manager doesn't even compile on Xcode 12.5.

It's very hard to evaluate this library for use in our project.
I'm pretty sure a lot of thought went into it, but as long as you cannot test it in couple of steps I don't think people will use it.

**Comment by daniellangh** [comment]
Added PR to fix compilation errors here: https://github.com/jVirus/expandable-collection-view-kit/pull/7

**Comment by eleev** [comment]
The PR #7 has been merged. Thanks a lot for your interest and contribution.

Regarding the example app: I totally agree that an example app is needed and more over it is a must. I will try to find a "window", so to speak, to make a good example app the described use case.
